apiVersion: plugin.halo.run/v1alpha1
kind: Plugin
metadata:
  name: PluginUnsplash
spec:
  enabled: true
  version: 1.0.0
  requires: ">=2.19.0"
  author:
    name: Halo
    website: https://github.com/halo-dev
  logo: logo.svg
  settingName: unsplash-settings
  configMapName: unsplash-settings
  repo: https://github.com/halo-sigs/plugin-unsplash
  homepage: https://www.halo.run/store/apps/app-NRcGw
  issues: https://github.com/halo-sigs/plugin-unsplash/issues
  displayName: "Unsplash"
  description: "提供从 Unsplash 选择或转存图片的能力"
  license:
    - name: "GPL-3.0"
      url: "https://github.com/halo-sigs/plugin-unsplash/blob/main/LICENSE"

